### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by keiraokimoto** [LoveMyDogs/P3T8_ezkg#2]
<< = Half done

## Scrum Master: 
- [x] Help with backend/frontend (connecting API and HTML/MD files)<<
   - [x] Organize/plan how to link backend and frontend
- [x] Delegate tasks to other roles
- [x] Test to ensure sites work
- [x] Error spotting
- *Will probably end up adding data to APIs*

## DevOps:
- [x] Fix Nginx configuration/Dockerfile configuration
- [x] Update and build site when needed
- [x] Test to ensure building was done correctly; fix those errors if needed
- [x] Restart/kill server when necessary
- [x] Support backend/frontend with connecting API to HTML/MD quiz page<<
- [x] Error spotting
- *Will probably end up adding data to APIs as well*

## Backend:
- [x] Create API template
   - [x] Add data for APStats<<
   - [x] Add data for APCalc<<
   - [x] Add data for Physics<<
- [x] Work with frontend to connect API to HTML/MD quiz page<<
- [x] Link 'check answer' function to the API, have it return the score
- [x] Display 'correct' and 'wrong' results (loop) for questions
- [x] Fix the images, need to add 'isImage = true' and then 'image: _images/FILENAME.png'<<

## Frontend:
- [x] Create HTML homepage and format
- [x] Format quiz page
- [x] Pull API from backend into HTML/MD (with backend)<<
- [x] Set the radio buttons to take only 1 answer (not just select all radio buttons), then link the radio button results to the 'check answer' (Google this)
- [x] Link the solution pages, then make sure they go to the next question
- [x] Create final/end page
- [x] Link the final/end page to calculate a score then also have a button that returns to the homepage/topic (ie, physics) homepage (can use an href link and add the end page as another html bc the main quiz page has a lot of code)
- [x] Finish designing the pages and make it not look ugly<<
